# contenedor ubuntu willy v.0.1
FROM ubuntu:18.04
RUN apt-get update -y
RUN apt-get install apache2 -y 
RUN apt-get install ngyx -y 
RUN apt-get install terminator
ENTRYPOINT echo "instalacion exitosa"